### ISSUE TITLE
Handling paths with space on Windows

### ISSUE THREAD

**Issue by CAMOBAP795** [metanorma/metanorma#100]
Based on information passed from @manuel489 puppeteer (or metanorma) have problems with processing paths with spaces 

```
$ bundle exec metanorma --type ogc --extensions pdf sources/00-027/document.adoc
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from C:/tools/ruby25/lib/ruby/gems/2.5.0/specifications/sterile-1.0.14.gemspec:15.
Style: Abstract is missing!
Style: Keywords are missing!
Style: Preface is missing!
Style: Submitters is missing!
Style Warning: (XML Line 000111): Hanging paragraph in clause
Style Warning: (XML Line 000141): Hanging paragraph in clause
Style Warning: (XML Line 000151): Hanging paragraph in clause
Style Warning: (XML Line 000154): Hanging paragraph in clause
Style Warning: (XML Line 000179): Hanging paragraph in clause
Style Warning: (XML Line 000179): Hanging paragraph in clause
Style Warning: (XML Line 000271): Hanging paragraph in clause
Style Warning: (XML Line 000301): Hanging paragraph in clause
Syntax: (XML Line 000009:6): character content of element "on" invalid; must be a string matching the regular expression "([\+\-]?\d{4})((-?)((0[1-9]|1[0-2])((-?)([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-2])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6]))))?"
Syntax: (XML Line 000172:75): element "clause" not allowed here; expected element "abstract" or "foreword"
Syntax: (XML Line 000178:98): element "clause" not allowed here; expected element "abstract" or "foreword"
Syntax: (XML Line 000194:111): element "clause" not allowed here; expected element "abstract" or "foreword"
Syntax: (XML Line 000197:20): element "preface" incomplete; missing required element "foreword"
Syntax: (XML Line 000531:16): element "ogc-standard" incomplete; missing required element "bibliography"
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-1.0.0/lib/metanorma/output/pdf.rb:18:in `convert': net::ERR_FILE_NOT_FOUND at file://D:/Dropbox/Trabajo/Freelancing/Upwork (RuntimeError)
Error: net::ERR_FILE_NOT_FOUND at file://D:/Dropbox/Trabajo/Freelancing/Upwork
    at navigate (C:\Users\Manuel\AppData\Roaming\npm\node_modules\puppeteer\lib\FrameManager.js:120:37)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\Manuel\AppData\Roaming\npm\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.goto (C:\Users\Manuel\AppData\Roaming\npm\node_modules\puppeteer\lib\Page.js:674:49)
    at Page.<anonymous> (C:\Users\Manuel\AppData\Roaming\npm\node_modules\puppeteer\lib\helper.js:112:23)
    at createPdf (C:\tools\ruby25\lib\ruby\gems\2.5.0\gems\metanorma-1.0.0\bin\metanorma-pdf.js:16:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/isodoc-1.0.22/lib/isodoc/pdf_convert.rb:33:in `convert'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-ogc-1.0.3/lib/metanorma/ogc/processor.rb:36:in `output'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-1.0.0/lib/metanorma/compile.rb:203:in `block in process_extensions'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-1.0.0/lib/metanorma/compile.rb:194:in `each'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-1.0.0/lib/metanorma/compile.rb:194:in `process_extensions'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-1.0.0/lib/metanorma/compile.rb:20:in `compile'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-cli-1.2.10.2/lib/metanorma/cli/compiler.rb:41:in `compile_file'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-cli-1.2.10.2/lib/metanorma/cli/compiler.rb:29:in `compile'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-cli-1.2.10.2/lib/metanorma/cli/compiler.rb:33:in `compile'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-cli-1.2.10.2/lib/metanorma/cli/command.rb:35:in `compile'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-cli-1.2.10.2/lib/metanorma/cli.rb:60:in `start'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-cli-1.2.10.2/exe/metanorma:20:in `<top (required)>'
        from C:/tools/ruby25/bin/metanorma:23:in `load'
        from C:/tools/ruby25/bin/metanorma:23:in `<main>'
```

Full path is `D:\Dropbox\Trabajo\Freelancing\Upwork Jobs`

**Comment by CAMOBAP795** [comment]
@ronaldtse could you please prioritize this

**Comment by ronaldtse** [comment]
This looks like an issue of `metanorma-pdf.js`. Let's get this fixed quickly?

**Comment by opoudjis** [comment]
I've merged this, so you can close this now.

**Comment by ronaldtse** [comment]
Thanks!
