### ISSUE TITLE
Fix windows broken tests

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma#233]
Broken after https://github.com/metanorma/metanorma/commit/7328790ff5d035db4dd918714a84dd375593eab6

Can be seen here: https://github.com/metanorma/metanorma/actions/runs/1678235597

**Comment by opoudjis** [comment]
Yes, I've just noticed this myself. Unfortunately, it's PC-specific, so I'm struggling to work out what has gone wrong. But this is the sectionsplit functionality now compiling in a separate, temporary directory, so that parallel execution of different formats would not overwrite each other. The code changes involved are in https://github.com/metanorma/metanorma/commit/7328790ff5d035db4dd918714a84dd375593eab6 , but they depend on code changes in isodoc gem, https://github.com/metanorma/isodoc/commit/bd5b1bed84891eebf53b01581f0a139dae99e2e4

**Comment by ronaldtse** [comment]
I think we should not merge failing PRs. @CAMOBAP are you able to help with this?

Failure:
```
2022-01-10T15:58:59.4804922Z Failures:
2022-01-10T15:58:59.4805343Z 
2022-01-10T15:58:59.4806127Z   1) Metanorma::Compile processes section split HTML
2022-01-10T15:58:59.4807014Z      Failure/Error: expect(File.exist?("#{f}/index.html")).to be true
2022-01-10T15:58:59.4807635Z 
2022-01-10T15:58:59.4808112Z        expected true
2022-01-10T15:58:59.4808646Z             got false
2022-01-10T15:58:59.4809333Z      # ./spec/compile_spec.rb:531:in `block (2 levels) in <top (required)>'
2022-01-10T15:58:59.4810192Z      # ./spec/compile_spec.rb:18:in `block (2 levels) in <top (required)>'
2022-01-10T15:58:59.4811354Z      # ./vendor/bundle/ruby/3.0.0/gems/rspec-command-1.0.3/lib/rspec_command.rb:47:in `block (2 levels) in <module:RSpecCommand>'
2022-01-10T15:58:59.4813208Z      # ./vendor/bundle/ruby/3.0.0/gems/rspec-command-1.0.3/lib/rspec_command.rb:45:in `block in <module:RSpecCommand>'
2022-01-10T15:58:59.4814244Z      # ./spec/spec_helper.rb:30:in `block (4 levels) in <top (required)>'
2022-01-10T15:58:59.4815235Z      # ./spec/spec_helper.rb:30:in `chdir'
2022-01-10T15:58:59.4816010Z      # ./spec/spec_helper.rb:30:in `block (3 levels) in <top (required)>'
2022-01-10T15:58:59.4817331Z      # ./spec/spec_helper.rb:24:in `block (2 levels) in <top (required)>'
2022-01-10T15:58:59.4818317Z 
2022-01-10T15:58:59.4819037Z Finished in 2 minutes 15.6 seconds (files took 5.33 seconds to load)
2022-01-10T15:58:59.4819800Z 57 examples, 1 failure
```

**Comment by CAMOBAP** [comment]
@ronaldtse there are several windows failures in my list which I will have a look after relaton-bib-py

**Comment by ronaldtse** [comment]
All Windows tests are passing now. Closing.
