### ISSUE TITLE
Error: undefined method `bibitem_lookup'

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma#291]
Source issue: https://github.com/metanorma/mn-native-pdf-bsi/issues/41

The source document: https://github.com/metanorma/mn-samples-bsi/tree/main/sources/pas-2035-2030-collection

`bundle exec metanorma site generate --agree-to-terms` causes the error:

```
Process document.html: 17:44:21
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/metanorma-0bd8649f788b/lib/metanorma/collection_fileparse.rb:133:in `svgmap_resolve': undefined method `bibitem_lookup' for #<IsoDoc::Convert:0x00000214920bbd20 @options={:bodyfont=>"Arial", :headerfont=>"Arial", :monospacefont=>"Courier New"}, @htmlstylesheet_name=nil, @wordstylesheet_name=nil, @htmlstylesheet_override_name=nil, @wordstylesheet_override_name=nil, @standardstylesheet_name=nil, @header=nil, @htmlcoverpage=nil, @wordcoverpage=nil, @htmlintropage=nil, @wordintropage=nil, @scripts="C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/isodoc-d1c990ffd36a/lib/isodoc/base_style/scripts.html", @scripts_pdf=nil, @scripts_override=nil, @htmlToClevels=2, @wordToClevels=2, @tocfigures=nil, @toctables=nil, @tocrecommendations=nil, @normalfontsize=nil, @smallerfontsize=nil, @monospacefontsize=nil, @footnotefontsize=nil, @fontist_fonts=nil, @fontlicenseagreement=nil, @termdomain="", @termexample=false, @note=false, @sourcecode=false, @footnotes=[], @comments=[], @in_footnote=false, @in_comment=false, @in_table=false, @in_figure=false, @seen_footnote=#<Set: {}>, @c=#<HTMLEntities:0x00000214920baf38 @flavor="xhtml1">, @openmathdelim="`", @closemathdelim="`", @maxwidth=1200, @maxheight=800, @bookmarks_allocated={"X"=>true}, @fn_bookmarks={}, @libdir="C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/isodoc-d1c990ffd36a/lib/isodoc", @baseassetpath=nil, @tmpimagedir_suffix="_29edb62f3c19f1af_images", @tmpfilesdir_suffix="_ec183013821308e9_files", @sourcefilename=nil, @files_to_delete=[], @tempfile_cache=[], @i18nyaml=nil, @lang="en", @script="Latn", @locale=nil, @localizenumber=nil, @ulstyle=nil, @olstyle=nil, @datauriimage=nil, @suppressheadingnumbers=nil, @break_up_urls_in_tables=nil, @suppressasciimathdup=nil, @aligncrosselements=nil, @modspecidentifierbase=nil, @sourcehighlighter=nil, @sectionsplit=false, @bare=nil, @semantic_xml_insert=true> (NoMethodError)

      isodoc.bibitem_lookup(docxml)\r
            ^^^^^^^^^^^^^^^
Did you mean?  bibitem_ref_code
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/metanorma-0bd8649f788b/lib/metanorma/collection_fileparse.rb:98:in `update_xrefs'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/metanorma-0bd8649f788b/lib/metanorma/collection_fileprocess.rb:227:in `block in files'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/metanorma-0bd8649f788b/lib/metanorma/collection_fileprocess.rb:220:in `each'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/metanorma-0bd8649f788b/lib/metanorma/collection_fileprocess.rb:220:in `each_with_index'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/metanorma-0bd8649f788b/lib/metanorma/collection_fileprocess.rb:220:in `files'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/metanorma-0bd8649f788b/lib/metanorma/collection_renderer.rb:77:in `render'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/metanorma-0bd8649f788b/lib/metanorma/collection.rb:100:in `render'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.1/lib/metanorma/cli/collection.rb:19:in `render'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.1/lib/metanorma/cli/collection.rb:14:in `render'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.1/lib/metanorma/cli/site_generator.rb:183:in `dequeue_jobs'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.1/lib/metanorma/cli/site_generator.rb:38:in `generate'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.1/lib/metanorma/cli/site_generator.rb:26:in `generate'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.1/lib/metanorma/cli/commands/site.rb:33:in `generate'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.1/lib/metanorma/cli.rb:34:in `start'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.1/exe/metanorma:25:in `block in <top (required)>'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.1/exe/metanorma:43:in `<top (required)>'
        from C:/tools/ruby31/bin/metanorma:25:in `load'
        from C:/tools/ruby31/bin/metanorma:25:in `<main>'
```

How to repeat:
```
git clone https://github.com/metanorma/mn-samples-bsi
cd mn-samples-bsi
bundle update
cd sources/pas-2035-2030-collection
bundle exec metanorma site generate --agree-to-terms
```

**Comment by opoudjis** [comment]
Issue has gone away, document now compiles fine. @Intelligent2013 please remember to assign me issues that relate to Metanorma bugs...
