### ISSUE TITLE
Error: patron-0.13.3 installation issue

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma#293]
From https://github.com/metanorma/mn-native-pdf/actions/runs/5011909961/jobs/8983250062

```
Installing relaton-iec 1.14.4
Using sparql 3.2.5
Using rdf-turtle 3.2.1
Using lutaml-xmi 0.2.3
Using word-to-markdown 1.1.8
Installing rdf-vocab 3.2.6
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/home/runner/work/mn-native-pdf/mn-native-pdf/vendor/bundle/ruby/2.7.0/gems/patron-0.13.3/ext/patron
/opt/hostedtoolcache/Ruby/2.7.8/x64/bin/ruby -I
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/2.7.0 -r
./siteconf20[230](https://github.com/metanorma/mn-native-pdf/actions/runs/5011909961/jobs/8983250062#step:5:236)518-3978-7vgyx3.rb extconf.rb
checking for curl-config... no
checking for -lcurl... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/hostedtoolcache/Ruby/2.7.8/x64/bin/$(RUBY_BASE_NAME)
	--with-curl-dir
	--without-curl-dir
	--with-curl-include
	--without-curl-include=${curl-dir}/include
	--with-curl-lib
	--without-curl-lib=${curl-dir}/lib
	--with-curl-config
	--without-curl-config
	--with-curllib
	--without-curllib
extconf.rb:10:in `<main>':   Can't find libcurl or curl/curl.h (RuntimeError)

Try passing --with-curl-config, --with-curl-dir, or --with-curl-lib and
--with-curl-include
  options to extconf.

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

/home/runner/work/mn-native-pdf/mn-native-pdf/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/patron-0.13.3/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/home/runner/work/mn-native-pdf/mn-native-pdf/vendor/bundle/ruby/2.7.0/gems/patron-0.13.3
for inspection.
Results logged to
/home/runner/work/mn-native-pdf/mn-native-pdf/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/patron-0.13.3/gem_make.out

/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/2.7.0/rubygems/ext/builder.rb:99:in
`run'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/2.7.0/rubygems/ext/ext_conf_builder.rb:48:in
`block in build'
  /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/2.7.0/tempfile.rb:[291](https://github.com/metanorma/mn-native-pdf/actions/runs/5011909961/jobs/8983250062#step:5:297):in `open'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/2.7.0/rubygems/ext/ext_conf_builder.rb:30:in
`build'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/2.7.0/rubygems/ext/builder.rb:169:in
`block in build_extension'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/2.7.0/rubygems/ext/builder.rb:165:in
`synchronize'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/2.7.0/rubygems/ext/builder.rb:165:in
`build_extension'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/2.7.0/rubygems/ext/builder.rb:210:in
`block in build_extensions'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/2.7.0/rubygems/ext/builder.rb:207:in
`each'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/2.7.0/rubygems/ext/builder.rb:207:in
`build_extensions'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/2.7.0/rubygems/installer.rb:844:in
`build_extensions'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.13/lib/bundler/rubygems_gem_installer.rb:72:in
`build_extensions'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.13/lib/bundler/rubygems_gem_installer.rb:28:in
`install'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.13/lib/bundler/source/rubygems.rb:198:in
`install'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.13/lib/bundler/installer/gem_installer.rb:54:in
`install'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.13/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.13/lib/bundler/installer/parallel_installer.rb:156:in
`do_install'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.13/lib/bundler/installer/parallel_installer.rb:147:in
`block in worker_pool'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.13/lib/bundler/worker.rb:62:in
`apply_func'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.13/lib/bundler/worker.rb:57:in
`block in process_queue'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.13/lib/bundler/worker.rb:54:in
`loop'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.13/lib/bundler/worker.rb:54:in
`process_queue'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.13/lib/bundler/worker.rb:90:in
`block (2 levels) in create_threads'

An error occurred while installing patron (0.13.3), and Bundler cannot continue.

In Gemfile:
  metanorma-cli was resolved to 1.7.1, which depends on
    metanorma-bipm was resolved to 2.2.9, which depends on
      metanorma-generic was resolved to 2.4.2, which depends on
        metanorma-standoc was resolved to 2.4.3, which depends on
          metanorma was resolved to 1.5.9, which depends on
            isodoc was resolved to 2.5.4, which depends on
              relaton-cli was resolved to 1.15.4, which depends on
                relaton was resolved to 1.15.2, which depends on
                  relaton-bsi was resolved to 1.14.6, which depends on
                    algolia was resolved to 2.3.1, which depends on
                      faraday was resolved to 1.9.0, which depends on
                        faraday-patron was resolved to 2.0.1, which depends on
                          patron
Error: The process '/opt/hostedtoolcache/Ruby/2.7.8/x64/bin/bundle' failed with exit code 5
```

**Comment by Intelligent2013** [comment]
The issue occurs on Ubuntu and Debian only.

**Comment by Intelligent2013** [comment]
> extconf.rb:10:in `<main>':   Can't find libcurl or curl/curl.h (RuntimeError)

I'll try to add `libcurl` into ubuntu and debian .yml.

**Comment by Intelligent2013** [comment]
Fixed. Added `libcurl4-gnutls-dev` into `ubuntu.yml` and `debian.yml`.
