### ISSUE TITLE
Windows: bundle update crash 'Can't find libcurl or curl/curl.h'

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma#294]
```
Microsoft Windows [Version 10.0.19044.2965]
(c) Microsoft Corporation. All rights reserved.

D:\Work\Metanorma\Stepmod\Result.adoc\fundamentals_of_product_description_and_support>bundle update
Fetching gem metadata from https://rubygems.org/..............
Resolving dependencies...
Using rake 13.0.6
Using concurrent-ruby 1.2.2
Using minitest 5.18.0
Using public_suffix 5.0.1
Using faraday-em_http 1.0.0
Using faraday-em_synchrony 1.0.0
Using faraday-excon 1.1.0
Using httpclient 2.8.3
Using multipart-post 2.3.0
Using faraday-net_http 2.1.0
Using connection_pool 2.4.1
Using ruby2_keywords 0.0.5
Using faraday-rack 1.0.0
Using faraday-retry 1.0.3
Using multi_json 1.15.0
Using arr-pm 0.0.12
Using asciidoctor 2.0.20
Using asciimath 2.0.5
Using htmlentities 4.3.4
Using racc 1.6.2
Using rsec 1.0.0
Using bundler 2.4.10
Using latex-decode 0.4.0
Using builder 3.2.4
Using camertron-eprun 1.1.1
Using cldr-plurals-runtime-rb 1.1.0
Using cliver 0.3.2
Using cnccs 0.1.6
Using coderay 1.1.3
Using csv 3.2.6
Using date 3.3.3
Using descriptive_statistics 2.5.1
Using unf_ext 0.0.8.2 (x64-mingw-ucrt)
Using link_header 0.0.8
Using scanf 1.0.0
Using matrix 0.4.2
Using unicode-types 1.8.0
Using ffi 1.15.5 (x64-mingw-ucrt)
Using ruby-ole 1.2.12.2
Using rubyzip 2.3.2
Using seven-zip 1.4.2
Using thor 1.0.1
Using rchardet 1.8.0
Using mime-types-data 3.2023.0218.1
Using plist 3.7.0
Using socksify 1.7.1
Using ttfunk 1.7.0
Using gb-agencies 0.0.7
Using graphql 1.13.6
Using temple 0.10.1
Using tilt 2.1.0
Using hashie 4.1.0
Using hollaback 0.1.1
Using image_size 3.2.0
Using plane1converter 0.0.1
Using ox 2.14.16
Using parslet 2.0.0
Using thread_safe 0.3.6
Using uuidtools 2.2.0
Using iso-639 0.3.6
Using iso639 1.3.2
Using liquid 5.4.0
Using marcel 1.0.2
Using mn2pdf 1.70
Using mdb 0.5.0
Using timeout 0.3.2
Using net-http-digest_auth 1.4.1
Using rubyntlm 0.6.3
Using webrobots 0.1.2
Using webrick 1.8.1
Using isoics 0.1.11
Using mini_portile2 2.8.2
Using optout 0.0.2
Using lightly 0.4.0
Using json-canonicalization 0.3.2
Using rack 3.0.7
Using rexml 3.2.5
Using logger 1.5.3
Using stringio 3.0.6
Using roman-numerals 0.3.0
Using rouge 4.1.1
Using method_source 1.0.0
Using unicode2latex 0.0.6
Using mnconvert 1.52.0
Using tokenizer 0.3.0
Using metanorma-ietf-data 0.2.0
Using i18n 1.13.0
Using tzinfo 2.0.6
Using addressable 2.8.4
Using hamster 3.0.0
Using faraday-httpclient 2.0.1
Using faraday-multipart 1.0.4
Using net-http-persistent 4.0.2
Using nokogiri 1.14.4 (x64-mingw-ucrt)
Using bibtex-ruby 6.0.0
Using unf 0.1.4
Using time 0.2.2
Using rdf 3.2.10
Using emf2svg 1.4.3 (x64-mingw-ucrt)
Using ffi-libarchive 1.1.3
Using ffi-compiler2 2.0.1
Using extract_ttc 0.3.6 (x64-mingw-ucrt)
Using sys-uname 1.2.3
Using sys-proctable 1.3.0
Using pngcheck 0.3.1 (x64-mingw-ucrt)
Using expressir 1.2.8 (x64-mingw-ucrt)
Using relaton-index 0.2.0
Using mime-types 3.4.1
Using haml 5.2.2
Using thor-hollaback 0.2.1
Using plurimath 0.3.2
Using pubid-core 1.8.0
Using net-protocol 0.2.1
Using ruby-jing 0.0.3
Using psych 5.1.0
Using ruby-graphviz 1.2.5
Using pry 0.14.2
Using activesupport 7.0.4.3
Using bcp47 0.3.3
Using twitter_cldr 6.11.5
Using tzinfo-data 1.2023.3
Using css_parser 1.14.0
Using down 5.4.1
Using git 1.18.0
Using faraday-net_http_persistent 2.0.2
Using asciimath2unitsml 0.4.3
Using iev 0.3.1
Using sterile 1.0.24
Using mathml2asciimath 0.0.14
Using nokogiri-styles 0.1.2
Using reverse_markdown 1.4.0
Using domain_name 0.5.20190701
Using relaton-bib 1.14.11
Using sxp 1.2.4
Using ffi-libarchive-binary 0.3.0 (x64-mingw-ucrt)
Using json-ld 3.2.5
Using rdf-aggregate-repo 3.2.1
Using rdf-xsd 3.2.1
Using sparql-client 3.2.1
Using rdf-hamster-repo 3.2.1
Using rdf-isomorphic 3.2.1
Using rdf-json 3.2.0
Using rdf-vocab 3.2.6
Using rdf-normalize 0.5.1
Using rdf-ordered-repo 3.2.1
Using libmspack 0.10.1.2
Using lutaml-express 0.2.1
Using html2doc 1.5.4
Using pubid-iso 0.5.3
Using net-ftp 0.1.3
Using graphql-client 0.16.0
Using lutaml-uml 0.4.3
Using premailer 1.11.1
Using metanorma-utils 1.5.0
Using http-cookie 1.0.5
Using relaton-iso-bib 1.14.0
Using relaton-ietf 1.14.3
Using relaton-nist 1.14.3
Using relaton-iho 1.14.3
Using relaton-omg 1.14.0
Using ebnf 2.3.2
Using json-ld-preloaded 3.2.2
Using rdf-reasoner 0.8.0
Using rdf-trix 3.2.0
Using yaml-ld 0.0.2
Using rdf-rdfa 3.2.2
Using rdf-tabular 3.2.1
Using excavate 0.3.3
Using relaton-3gpp 1.14.3
Using isodoc-i18n 1.1.8
Using lutaml-xmi 0.2.3
Using word-to-markdown 1.1.8
Using mechanize 2.8.5
Using relaton-gb 1.14.0
Using relaton-iec 1.14.4
Using sparql 3.2.5
Using rdf-turtle 3.2.1
Using rdf-microdata 3.2.1
Using rdf-rdfxml 3.2.1
Using fontist 1.15.1
Using mn-requirements 0.3.3
Using relaton-render 0.5.12
Using lutaml 0.7.5
Using relaton-cie 1.14.0
Using relaton-cen 1.14.1
Using relaton-ecma 1.14.3
Using relaton-itu 1.14.1
Using relaton-jis 1.14.1
Using relaton-oasis 1.14.3
Using reverse_adoc 0.3.6
Using ld-patch 3.2.0
Using rdf-n3 3.2.1
Using rdf-trig 3.2.0
Using shacl 0.3.0
Using shex 0.7.1
Using linkeddata 3.2.1
Using relaton-w3c 1.14.2
Installing patron 0.13.3 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/patron-0.13.3/ext/patron
C:/tools/ruby31/bin/ruby.exe -I C:/tools/ruby31/lib/ruby/3.1.0 -r
./siteconf20230521-14716-x6uuj7.rb extconf.rb
checking for curl-config... no
checking for -lcurl... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/tools/ruby31/bin/$(RUBY_BASE_NAME)
        --with-curl-dir
        --without-curl-dir
        --with-curl-include
        --without-curl-include=${curl-dir}/include
        --with-curl-lib
        --without-curl-lib=${curl-dir}/lib
        --with-curl-config
        --without-curl-config
        --with-curllib
        --without-curllib
extconf.rb:10:in `<main>':   Can't find libcurl or curl/curl.h (RuntimeError)

Try passing --with-curl-config, --with-curl-dir, or --with-curl-lib and
--with-curl-include
  options to extconf.

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

C:/tools/ruby31/lib/ruby/gems/3.1.0/extensions/x64-mingw-ucrt/3.1.0/patron-0.13.3/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/patron-0.13.3 for inspection.
Results logged to
C:/tools/ruby31/lib/ruby/gems/3.1.0/extensions/x64-mingw-ucrt/3.1.0/patron-0.13.3/gem_make.out

  C:/tools/ruby31/lib/ruby/3.1.0/rubygems/ext/builder.rb:95:in `run'
C:/tools/ruby31/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:47:in `block
in build'
  C:/tools/ruby31/lib/ruby/3.1.0/tempfile.rb:317:in `open'
  C:/tools/ruby31/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:26:in `build'
C:/tools/ruby31/lib/ruby/3.1.0/rubygems/ext/builder.rb:161:in
`build_extension'
C:/tools/ruby31/lib/ruby/3.1.0/rubygems/ext/builder.rb:195:in `block in
build_extensions'
  C:/tools/ruby31/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `each'
C:/tools/ruby31/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in
`build_extensions'
  C:/tools/ruby31/lib/ruby/3.1.0/rubygems/installer.rb:853:in `build_extensions'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/bundler-2.4.10/lib/bundler/rubygems_gem_installer.rb:72:in
`build_extensions'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/bundler-2.4.10/lib/bundler/rubygems_gem_installer.rb:28:in
`install'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/bundler-2.4.10/lib/bundler/source/rubygems.rb:200:in
`install'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/bundler-2.4.10/lib/bundler/installer/gem_installer.rb:54:in
`install'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/bundler-2.4.10/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/bundler-2.4.10/lib/bundler/installer/parallel_installer.rb:156:in
`do_install'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/bundler-2.4.10/lib/bundler/installer/parallel_installer.rb:147:in
`block in worker_pool'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/bundler-2.4.10/lib/bundler/worker.rb:62:in
`apply_func'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/bundler-2.4.10/lib/bundler/worker.rb:57:in
`block in process_queue'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/bundler-2.4.10/lib/bundler/worker.rb:54:in
`loop'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/bundler-2.4.10/lib/bundler/worker.rb:54:in
`process_queue'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/bundler-2.4.10/lib/bundler/worker.rb:90:in
`block (2 levels) in create_threads'

An error occurred while installing patron (0.13.3), and Bundler cannot continue.

In Gemfile:
  metanorma-cli was resolved to 1.7.1, which depends on
    metanorma-bipm was resolved to 2.2.9, which depends on
      metanorma-generic was resolved to 2.4.2, which depends on
        metanorma-standoc was resolved to 2.4.3, which depends on
          metanorma was resolved to 1.5.9, which depends on
            isodoc was resolved to 2.5.4, which depends on
              relaton-cli was resolved to 1.15.4, which depends on
                relaton was resolved to 1.15.2, which depends on
                  relaton-bsi was resolved to 1.14.6, which depends on
                    algolia was resolved to 2.3.1, which depends on
                      faraday was resolved to 1.9.0, which depends on
                        faraday-patron was resolved to 2.0.1, which depends on
                          patron
```

**Comment by Intelligent2013** [comment]
Gemfile:
```
source "https://rubygems.org"

gem "metanorma-cli"
```

**Comment by Intelligent2013** [comment]
Solution based on: https://stackoverflow.com/a/28781037/4031794

1. Download curl for Windows from https://curl.se/windows/ (https://curl.se/windows/dl-8.1.0_1/curl-8.1.0_1-win64-mingw.zip) and unpack .zip.

`/bin`:
```
curl-ca-bundle.crt
curl.exe
libcurl-x64.def
libcurl-x64.dll
```
`/include`:
```
brotli
curl
gsasl-mech.h
gsasl-version.h
gsasl.h
libssh2.h
libssh2_publickey.h
libssh2_sftp.h
nghttp2
nghttp3
ngtcp2
openssl
zconf.h
zdict.h
zlib.h
zstd.h
zstd_errors.h
```

`lib`:
```
libbrotlicommon.a
libbrotlidec.a
libcrypto.a
libcurl.a
libcurl.dll.a
libgsasl.a
libnghttp2.a
libnghttp3.a
libngtcp2.a
libngtcp2_crypto_openssl.a
libssh2.a
libssl.a
libz.a
libzstd.a
```
2. install `patron` gem:
```
gem install patron --platform=ruby -- -- --with-curl-lib="C:/curl-8.1.0_1-win64-mingw/lib" --with-curl-include="C:/curl-8.1.0_1-win64-mingw/include"
```
Note: the parameter `--with-curl-lib` in the SO answer points to the folder `.../bin`, but in my case `.../lib` should be specified.

```
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions with: '-- --with-curl-lib=C:/curl-8.1.0_1-win64-mingw/lib --with-curl-include=C:/curl-8.1.0_1-win64-mingw/include'
This could take a while...

Thank you for installing Patron. On OSX, make sure you are using libCURL with OpenSSL.
SecureTransport-based builds might cause crashes in forking environment.

For more info see https://github.com/curl/curl/issues/788
Successfully installed patron-0.13.3
Parsing documentation for patron-0.13.3
Installing ri documentation for patron-0.13.3
Done installing documentation for patron after 3 seconds
1 gem installed
```
