### ISSUE TITLE
Handle native SVG’s

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma#358]
Source issue: https://github.com/metanorma/mn2pdf/issues/239#issuecomment-1987206641
Related issues: https://github.com/metanorma/metanorma-bsi/issues/272, https://github.com/metanorma/mn2pdf/issues/177

There are cases when the SVG figures use the different fonts than used in the main text.

For instance, the main text font in the ISO documents is `Cambria`, but the fonts `sans-serif`, `Helvetica` and `monospace` are using the SVG image (Figure):
```
<svg xmlns="http://www.w3.org/2000/svg" ....>
...
<text fill="#000000" font-family="sans-serif" font-size="14" lengthAdjust="spacing" textLength="65" x="282.5" y="31.9951">Template</text>
...
<div style="display: inline-block; font-size: 12px; font-family: Helvetica; color: rgb(0, 0, 0); line-height: 1.2; pointer-events: none; white-space: normal; overflow-wrap: normal;">TBox <br/>
	<span style="color: rgba(0 , 0 , 0 , 0) ; font-family: monospace ; font-size: 0px">%3C</span></div>
</div>
...
</svg>
```

Note: `Helvetica` is the concrete font name, but `sans-serif` and `monospace` are generic-names.

When metanorma creates the PDF, it calls the fontist to install the fonts specified in:
- `processor.rb` in gem, for instance, https://github.com/metanorma/metanorma-iso/blob/main/lib/metanorma/iso/processor.rb:
```rb
      def fonts_manifest
        {
          "Cambria" => nil,
          "Cambria Math" => nil,
          "Times New Roman" => nil,
          "Source Han Sans" => nil,
          "Source Han Sans Normal" => nil,
          "Courier New" => nil,
          "Inter" => nil,
        }
      end
```
- document's attribute `:fonts:` (https://www.metanorma.org/author/ref/document-attributes/#visual-appearance)

Then, fonts installed/found by fontist pass to the `mn2pdf` via fontist manifest file (.yml).
`mn2pdf` uses these fonts to render the PDF.
For fonts which missing in the fontist manifest file, `mn2pdf` uses the replacement font 'Noto Sans'.

### Proposal to use the original fonts in the SVG:
- metanorma parses the attributes `font-family` in the SVG and pass the values into the fontist installation process (similar to the document attribute `:fonts:`).
- `fontist` installs the font in this sequence:
   - 1st - find the font in `family_name` and install it (currently)
   - 2nd - if font isn't found by `family_name`, then find it by `preferred_family_name` (currently we have to set the parameter `--preferred-family` obviously)
   - 3rd - if font isn't found by `preferred_family_name`, then find it by `full_name`
 - 4th - find by `post_script_name`

Example: fontist font specification for `ArialMT` (https://github.com/fontist/fontist/blob/2e1f15508932f9ef0f5c52c12066a0ff13699e49/spec/examples/import/webcore.yml#L119):
```yaml
- family_name: Arial
    type: Regular
    full_name: Arial
    post_script_name: ArialMT
```

- if `font-family` is family name like `sans-serif` or `monospace` (full list see in https://developer.mozilla.org/en-US/docs/Web/CSS/font-family), then `fontist` should pass the first found font (currently I don't know the algorithm) with name (`sans-serif` or `monospace`) in the manifest, for example:
```
monospace:
  Regular:
    full_name: monospace
    paths:
    - C:/Windows/Fonts/cour.ttf
```

**Comment by Intelligent2013** [comment]
Update from https://github.com/metanorma/metanorma-jis/issues/165:
there are cases when `font-family` in the SVG image contains the font weight, for example:
- `YuGothicUI-Regular`
- `YuGothicUI-Bold`
- `Calibri-Bold`

In this case, the font should be installed by the font family name without the font weight: `YuGothicUI`, `Calibri`, etc.

**Comment by ronaldtse** [comment]
@Intelligent2013 thank you for following up on this!

I think it's time for us to deal with this issue of embedded SVG images that uses fonts that are not included.

There are two use cases:
1. Replace the fonts stated in SVG with fonts available in the document/flavor. This is useful when the organization has strict rules to only use particular fonts even in vector images. The problem is that the images' internal layout may appear different, but it is expected.
2. Accept the SVG-specified fonts as necessary for compilation, and then find out how to obtain those fonts and install them.
    * If the fonts are available through Fontist, we can have a flag to ask Fontist to download/install them.
    * Otherwise, since Fontist only serves a limited number of fonts, this has to be mainly the author's responsibility, the author needs to either embed those glyphs in the SVG, or be warned by the Metanorma process that fonts in the SVGs cannot be rendered.

**Comment by ronaldtse** [comment]
We have run into this issue again for ISO 22726-1. The SVG diagrams originally use Cambria, but when they are rendered into Source Sans (due to default font) the spacing is messed up (as expected).

Source:
https://github.com/metanorma/iso-22726-1/pull/2

<img width="881" height="453" alt="Image" src="https://github.com/user-attachments/assets/b96b45cc-b7a7-4ab7-b7cc-fd642f48ac6a" />

Is it possible that we have these options?

Per document/flavor:
- override all images to use a specified font available in the font manifest (and how do I refer to it? What fonts are available?)

Per image:
- override all fonts in the SVG to a specified font available in the font manifest
- override individual fonts in the SVG to particular specified fonts available in the font manifest

That said, the question about that particular document is that Cambria is supported in ISO layout. Why is it replacing Cambria with Source Sans in rendering?

**Comment by Intelligent2013** [comment]
> Per document/flavor:
> 
> * override all images to use a specified font available in the font manifest (and how do I refer to it? What fonts are available?)

`mn2pdf` is working with fonts: 
- passed via `fontist`s manifest file. `fontist` creates the manifest file based on:
  - fonts determined in `https://github.com/metanorma/metanorma-iso/blob/main/lib/metanorma/iso/processor.rb`
   ```ruby
      def fonts_manifest
        {
          "Cambria" => nil,
          "Cambria Math" => nil,
          "Times New Roman" => nil,
          "Source Han Sans" => nil,
          "Source Han Sans Normal" => nil,
          "Courier New" => nil,
          "Inter" => nil,
        }
      end
   ```
    -  fonts from the document attribute `:fonts:`.

and 

- fonts from Apache FOP config in https://github.com/metanorma/mn2pdf/blob/main/src/main/resources/pdf_fonts_config.xml, but only if fonts are present on the machine. For instance, the font `Calibri` on my Win10 is available and will be used without replacement to Noto Sans, even if `Calibri` is missing in `processor.rb` and `:fonts:`.

Any another fonts will be replaced to the font Noto Sans.

> That said, the question about that particular document is that Cambria is supported in ISO layout. Why is it replacing Cambria with Source Sans in rendering?

Regarding the particular image from the screenshot above (https://github.com/metanorma/iso-22726-1/blob/conversion/sources/iso-22726-1_rev1_2026_static/images/svg/figure-05.svg)
The SVG contains the font `Calibri`
```xml
<text x="564.00" y="26.00" textLength="61" style="font-family:Calibri; font-weight:0; font-style:normal; font...
```
not `Cambria`, therefore it will be substituted by the font Noto Sans.


But I can't generate PDF properly due the errors:
```
SVG error: file:/D:/Work/Metanorma/repositories/iso-22726-1/sources/iso-22726-1_rev1_2026_static/:
The attribute "style" represents an invalid CSS declaration ("font-family:Calibri; font-weight:0; font-style:normal; font-size:10px; fill:#000000;fill-opacity:1.00; stroke:#000000; stroke-opacity:0.00 stroke-width:0; white-space: pre;").
Original message:
The number '0' represents an invalid value for the 'font-weight' property.
org.w3c.dom.DOMException: file:/D:/Work/Metanorma/repositories/iso-22726-1/sources/iso-22726-1_rev1_2026_static/:
The attribute "style" represents an invalid CSS declaration ("font-family:Calibri; font-weight:0; font-style:normal; font-size:10px; fill:#000000;fill-opacity:1.00; stroke:#000000; stroke-opacity:0.00 stroke-width:0; white-space: pre;").
Original message:
The number '0' represents an invalid value for the 'font-weight' property.
	at org.apache.batik.css.engine.CSSEngine.getCascadedStyleMap(CSSEngine.java:824)
	at org.apache.batik.css.engine.CSSEngine.getComputedStyle(CSSEngine.java:867)
	at org.apache.batik.bridge.CSSUtilities.getComputedStyle(CSSUtilities.java:81)
```
and PDF looks so:

<img width="1162" height="472" alt="Image" src="https://github.com/user-attachments/assets/a4c9f50c-8513-4636-8218-e01e1fb6953a" />

Let's see another SVG - https://github.com/metanorma/iso-22726-1/blob/conversion/sources/iso-22726-1_rev1_2026_static/images/svg/figure-04.svg, it contains the font-family:
```
font-family="Cambria,Cambria_MSFontService,sans-serif"
```

If first font `Cambria` is available, then it will be used, if not, then next font `Cambria_MSFontService` will be used if available, etc.
Or if glyph from first fonts is missing in the font, then glyph from 2nd font will be used, etc.

`mn2pdf` checks all fonts from the `font-family`, therefore we see this message in .pdf.err log:
```
WARNING: Font 'Cambria_MSFontService' (font name 'Cambria_MSFontService', font style 'normal', font weight 'normal') doesn't exist. Replaced by 'C:\Users\TestUser\.metanorma\fonts\NotoSans-Regular.ttf'.
WARNING: Font 'Cambria_MSFontService' (font name 'Cambria_MSFontService', font style 'normal', font weight 'bold') doesn't exist. Replaced by 'C:\Users\TestUser\.metanorma\fonts\NotoSans-Bold.ttf'.
WARNING: Font 'Cambria_MSFontService' (font name 'Cambria_MSFontService', font style 'italic', font weight 'normal') doesn't exist. Replaced by 'C:\Users\TestUser\.metanorma\fonts\NotoSans-Italic.ttf'.
WARNING: Font 'Cambria_MSFontService' (font name 'Cambria_MSFontService', font style 'italic', font weight 'bold') doesn't exist. Replaced by 'C:\Users\TestUser\.metanorma\fonts\NotoSans-BoldItalic.ttf'.
WARNING: Font 'sans-serif' (font name 'sans-serif', font style 'normal', font weight 'normal') doesn't exist. Replaced by 'C:\Users\TestUser\.metanorma\fonts\NotoSans-Regular.ttf'.
WARNING: Font 'sans-serif' (font name 'sans-serif', font style 'normal', font weight 'bold') doesn't exist. Replaced by 'C:\Users\TestUser\.metanorma\fonts\NotoSans-Bold.ttf'.
WARNING: Font 'sans-serif' (font name 'sans-serif', font style 'italic', font weight 'normal') doesn't exist. Replaced by 'C:\Users\TestUser\.metanorma\fonts\NotoSans-Italic.ttf'.
WARNING: Font 'sans-serif' (font name 'sans-serif', font style 'italic', font weight 'bold') doesn't exist. Replaced by 'C:\Users\TestUser\.metanorma\fonts\NotoSans-BoldItalic.ttf'.
```

But it doesn't mean that the font `Cambria_MSFontService` replaced by NotoSans really somewhere. It just warning. May be more correctly say 'Will be replaced by' instead of `Replaced by`.

Regarding you question:

>  Why is it replacing Cambria with Source Sans in rendering?

could you upload your image instance, looks the image on GH is not latest.

**Comment by Intelligent2013** [comment]
I've tried to fix the issue `The number '0' represents an invalid value for the 'font-weight' property.` by replacing `font-weight:0` to `font-weight:400`, but Adobe Acrobat show image with poorly readable text:
<img width="1155" height="570" alt="Image" src="https://github.com/user-attachments/assets/b466e665-4166-4a95-ac94-550797d66b7d" />

but Foxit Reader renders ok:

<img width="1374" height="697" alt="Image" src="https://github.com/user-attachments/assets/dcf51fc9-1beb-434e-842f-0f86c3b134ce" />
