### ISSUE TITLE
missing dependency? faraday-net_http_persistent 

### ISSUE THREAD

**Issue by jerstlouis** [metanorma/metanorma#387]
After an upgrade (`gem install metanorma-cli`) I had to manually do:

```
gem install faraday-net_http_persistent
```

for things to work, otherwise I would be getting a confusing error:

```
Fatal Error: undefined method `dependency' for Faraday::Adapter::NetHttpPersistent:Class
```

Could this be a missing dependency?

**Comment by opoudjis** [comment]
This is one for @andrew2net, raising in relaton.

**Comment by opoudjis** [comment]
@jerstlouis Could you please confirm that this has worked?

> Please update relaton-iso to v1.18.3 and relaton-bsi to v1.18.1

**Comment by jerstlouis** [comment]
@opoudjis Just:
```
gem install metanorma-cli
Successfully installed metanorma-cli-1.9.8
Parsing documentation for metanorma-cli-1.9.8
Done installing documentation for metanorma-cli after 0 seconds
1 gem installed
```

doesn't seem to do it...

Shouldn't it automatically pick up all the right dependencies?

**Comment by opoudjis** [comment]
I can't replicate, I do get `gem install metnaorma-cli` installing faraday-net_http_persistent 2.1.0.

I don't know what to tell you here; there may be a lag in propagating the gem out of rubygems. Could you try again, and tell us which version of relaton-bsi it installs? The restriction is new to 1.18.1, so if your install was still picking up 1.18.0, it would not be picking up the faraday restriction.

**Comment by jerstlouis** [comment]
@opoudjis When I did `gem install metnaorma-cli` it did not install any new `relaton-bsi` or `relation-iso`.

It had `relaton-iso-1.18.1` already installed. Error:

```
metanorma 21-038.adoc 
Fatal Error: undefined method `dependency' for Faraday::Adapter::NetHttpPersistent:Class
/home/jerome/.gem/ruby/3.0.0/gems/faraday-net_http_persistent-1.2.0/lib/faraday/adapter/net_http_persistent.rb:7:in `<class:NetHttpPersistent>': undefined method `dependency' for Faraday::Adapter::NetHttpPersistent:Class (NoMethodError)
	from /home/jerome/.gem/ruby/3.0.0/gems/faraday-net_http_persistent-1.2.0/lib/faraday/adapter/net_http_persistent.rb:6:in `<class:Adapter>'
	from /home/jerome/.gem/ruby/3.0.0/gems/faraday-net_http_persistent-1.2.0/lib/faraday/adapter/net_http_persistent.rb:4:in `<module:Faraday>'
	from /home/jerome/.gem/ruby/3.0.0/gems/faraday-net_http_persistent-1.2.0/lib/faraday/adapter/net_http_persistent.rb:3:in `<top (required)>'
	from /home/jerome/.gem/ruby/3.0.0/gems/faraday-net_http_persistent-1.2.0/lib/faraday/net_http_persistent.rb:3:in `require_relative'
	from /home/jerome/.gem/ruby/3.0.0/gems/faraday-net_http_persistent-1.2.0/lib/faraday/net_http_persistent.rb:3:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/jerome/.gem/ruby/3.0.0/gems/algolia-2.3.2/lib/algolia/transport/transport.rb:3:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/jerome/.gem/ruby/3.0.0/gems/algolia-2.3.2/lib/algolia.rb:31:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/jerome/.gem/ruby/3.0.0/gems/relaton-iso-1.18.2/lib/relaton_iso/hit_collection.rb:3:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/jerome/.gem/ruby/3.0.0/gems/relaton-iso-1.18.2/lib/relaton_iso/iso_bibliography.rb:5:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/jerome/.gem/ruby/3.0.0/gems/relaton-iso-1.18.2/lib/relaton_iso.rb:14:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/jerome/.gem/ruby/3.0.0/gems/relaton-1.18.1/lib/relaton/registry.rb:29:in `block in register_gems'
	from /home/jerome/.gem/ruby/3.0.0/gems/relaton-1.18.1/lib/relaton/registry.rb:28:in `each'
	from /home/jerome/.gem/ruby/3.0.0/gems/relaton-1.18.1/lib/relaton/registry.rb:28:in `register_gems'
	from /home/jerome/.gem/ruby/3.0.0/gems/relaton-1.18.1/lib/relaton/registry.rb:22:in `initialize'
	from /usr/lib/ruby/3.0.0/singleton.rb:127:in `new'
	from /usr/lib/ruby/3.0.0/singleton.rb:127:in `block in instance'
	from /usr/lib/ruby/3.0.0/singleton.rb:125:in `synchronize'
	from /usr/lib/ruby/3.0.0/singleton.rb:125:in `instance'
	from /home/jerome/.gem/ruby/3.0.0/gems/relaton-1.18.1/lib/relaton/db.rb:6:in `initialize'
	from /home/jerome/.gem/ruby/3.0.0/gems/relaton-1.18.1/lib/relaton/db.rb:552:in `new'
	from /home/jerome/.gem/ruby/3.0.0/gems/relaton-1.18.1/lib/relaton/db.rb:552:in `init_bib_caches'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-standoc-2.8.9/lib/metanorma/standoc/ref_queue.rb:220:in `init_bib_caches'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-standoc-2.8.9/lib/metanorma/standoc/init.rb:103:in `init_biblio'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-standoc-2.8.9/lib/metanorma/standoc/init.rb:12:in `init'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-standoc-2.8.9/lib/metanorma/standoc/base.rb:42:in `document1'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-standoc-2.8.9/lib/metanorma/standoc/base.rb:32:in `document'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-standoc-2.8.9/lib/metanorma/standoc/utils.rb:13:in `convert'
	from /home/jerome/.gem/ruby/3.0.0/gems/asciidoctor-2.0.23/lib/asciidoctor/document.rb:956:in `convert'
	from /home/jerome/.gem/ruby/3.0.0/gems/asciidoctor-2.0.23/lib/asciidoctor/convert.rb:120:in `convert'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-1.7.7/lib/metanorma/input/asciidoc.rb:17:in `process'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-1.7.7/lib/metanorma/processor.rb:21:in `input_to_isodoc'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-1.7.7/lib/metanorma/compile.rb:72:in `process_input_adoc'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-1.7.7/lib/metanorma/compile.rb:54:in `process_input'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-1.7.7/lib/metanorma/compile.rb:32:in `compile'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.9.8/lib/metanorma/cli/compiler.rb:45:in `compile_file'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.9.8/lib/metanorma/cli/compiler.rb:30:in `compile'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.9.8/lib/metanorma/cli/compiler.rb:35:in `compile'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.9.8/lib/metanorma/cli/command.rb:244:in `compile_document'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.9.8/lib/metanorma/cli/command.rb:48:in `block in compile'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.9.8/lib/metanorma/cli/command.rb:48:in `each'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.9.8/lib/metanorma/cli/command.rb:48:in `compile'
	from /home/jerome/.gem/ruby/3.0.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /home/jerome/.gem/ruby/3.0.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from /home/jerome/.gem/ruby/3.0.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/jerome/.gem/ruby/3.0.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /home/jerome/.gem/ruby/3.0.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.9.8/lib/metanorma/cli.rb:34:in `start'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.9.8/exe/metanorma:25:in `block in <top (required)>'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.9.8/exe/metanorma:43:in `<top (required)>'
	from /home/jerome/.gem/ruby/3.0.0/bin/metanorma:25:in `load'
	from /home/jerome/.gem/ruby/3.0.0/bin/metanorma:25:in `<main>'
```
Installing `relation-bsi` manually is what worked and installed the proper faraday-net_http_persistent:

```
gem install relaton-bsi
Fetching relaton-bsi-1.18.1.gem
Fetching faraday-net_http_persistent-2.1.0.gem
Successfully installed faraday-net_http_persistent-2.1.0
Successfully installed relaton-bsi-1.18.1
Parsing documentation for faraday-net_http_persistent-2.1.0
Installing ri documentation for faraday-net_http_persistent-2.1.0
Parsing documentation for relaton-bsi-1.18.1
Installing ri documentation for relaton-bsi-1.18.1
Done installing documentation for faraday-net_http_persistent, relaton-bsi after 0 seconds
2 gems installed
```

So it seems like the dependency from metanorma-cli on relaton-bsi was not set up correctly.

When I uninstall relation-bsi-1.18.1, I get no dependency error that metanorma-cli depends on it:

```
gem uninstall relaton-bsi

Select gem to uninstall:
 1. relaton-bsi-1.10.1
 2. relaton-bsi-1.13.0
 3. relaton-bsi-1.14.6
 4. relaton-bsi-1.18.0
 5. relaton-bsi-1.18.1
 6. All versions
> 5
Successfully uninstalled relaton-bsi-1.18.1
```

And now trying to re-install metanorma-cli, still does not install relation-bsi-1.18.1, and still causes the error:

```
gem install metanorma-cli
Successfully installed metanorma-cli-1.9.8
Parsing documentation for metanorma-cli-1.9.8
Done installing documentation for metanorma-cli after 0 seconds
1 gem installed
```

metanorma-cli needs a dependency on `relaton-bsi >= 1.18.1` or something.
(which really is odd considering it's a minor version upgrade and ideally minor version upgrades would not have such breaking dependencies).

**Comment by andrew2net** [comment]
@jerstlouis the problem with `faraday-net_http_persistent` was fixed in the latest relaton-bsi and relaton-iso. To update the gems that depends on Relaton we need to rerelease them all. It will be done with the next minor update.

**Comment by opoudjis** [comment]
I'm confused myself, because I don't get this behavior, but the next release is Monday after next for Metanorma

**Comment by jerstlouis** [comment]
@opoudjis you probably don't get this behavior because you either:
- already have  relaton-bsi >= 1.18.1 installed, or
- you do not have an older relation-bsi (e.g., 1.18.0) installed

The gem installing behavior (at least on my system) seems to always keep the older version around, which does increase the likelihood to run into such problems.

Tthis is nothing blocking for me after I figured out what the deendency issue was, so no urgency.

It's just that having these dependencies in order will prevent a lot of frustration from users just trying to use metanorma to test out their documents to compile, if they get such odd errors.

**Comment by opoudjis** [comment]
After a very long time, we have finally just finalised the release. Could you please check now, @jerstlouis ?

**Comment by jerstlouis** [comment]
@opoudjis Doesn't seem to be working yet?

```
Rainbow:[jerome]:~$ gem uninstall relaton-bsi

Select gem to uninstall:
 1. relaton-bsi-1.10.1
 2. relaton-bsi-1.13.0
 3. relaton-bsi-1.14.6
 4. relaton-bsi-1.18.0
 5. relaton-bsi-1.18.1
 6. All versions
> 5
Successfully uninstalled relaton-bsi-1.18.1
Rainbow:[jerome]:~$ gem uninstall faraday-net_http_persistent

Select gem to uninstall:
 1. faraday-net_http_persistent-1.2.0
 2. faraday-net_http_persistent-2.1.0
 3. All versions
> 2
Successfully uninstalled faraday-net_http_persistent-2.1.0
Rainbow:[jerome]:~$ gem install metanorma-cli
Fetching concurrent-ruby-1.3.1.gem
Fetching ffi-1.17.0-x86_64-linux-gnu.gem
Fetching metanorma-cli-1.10.0.gem
Fetching metanorma-2.0.0.gem
Fetching mn2pdf-1.90.gem
Fetching shale-1.1.0.gem
Fetching bundler-2.5.11.gem
Successfully installed concurrent-ruby-1.3.1
Successfully installed ffi-1.17.0-x86_64-linux-gnu
Successfully installed bundler-2.5.11
Successfully installed mn2pdf-1.90
Successfully installed shale-1.1.0
Successfully installed metanorma-2.0.0
Successfully installed metanorma-cli-1.10.0
Parsing documentation for concurrent-ruby-1.3.1
Installing ri documentation for concurrent-ruby-1.3.1
Parsing documentation for ffi-1.17.0-x86_64-linux-gnu
Installing ri documentation for ffi-1.17.0-x86_64-linux-gnu
Parsing documentation for bundler-2.5.11
Installing ri documentation for bundler-2.5.11
Parsing documentation for mn2pdf-1.90
Installing ri documentation for mn2pdf-1.90
Parsing documentation for shale-1.1.0
Installing ri documentation for shale-1.1.0
Parsing documentation for metanorma-2.0.0
Installing ri documentation for metanorma-2.0.0
Parsing documentation for metanorma-cli-1.10.0
Installing ri documentation for metanorma-cli-1.10.0
Done installing documentation for concurrent-ruby, ffi, bundler, mn2pdf, shale, metanorma, metanorma-cli after 4 seconds
7 gems installed

Rainbow:[jerome]:~/specs/ogcapi-maps/core/standard$ metanorma 20-058.adoc 
Fatal Error: undefined method `dependency' for Faraday::Adapter::NetHttpPersistent:Class
/home/jerome/.gem/ruby/3.0.0/gems/faraday-net_http_persistent-1.2.0/lib/faraday/adapter/net_http_persistent.rb:7:in `<class:NetHttpPersistent>': undefined method `dependency' for Faraday::Adapter::NetHttpPersistent:Class (NoMethodError)
	from /home/jerome/.gem/ruby/3.0.0/gems/faraday-net_http_persistent-1.2.0/lib/faraday/adapter/net_http_persistent.rb:6:in `<class:Adapter>'
	from /home/jerome/.gem/ruby/3.0.0/gems/faraday-net_http_persistent-1.2.0/lib/faraday/adapter/net_http_persistent.rb:4:in `<module:Faraday>'
	from /home/jerome/.gem/ruby/3.0.0/gems/faraday-net_http_persistent-1.2.0/lib/faraday/adapter/net_http_persistent.rb:3:in `<top (required)>'
	from /home/jerome/.gem/ruby/3.0.0/gems/faraday-net_http_persistent-1.2.0/lib/faraday/net_http_persistent.rb:3:in `require_relative'
	from /home/jerome/.gem/ruby/3.0.0/gems/faraday-net_http_persistent-1.2.0/lib/faraday/net_http_persistent.rb:3:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/jerome/.gem/ruby/3.0.0/gems/algolia-2.3.2/lib/algolia/transport/transport.rb:3:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/jerome/.gem/ruby/3.0.0/gems/algolia-2.3.2/lib/algolia.rb:31:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/jerome/.gem/ruby/3.0.0/gems/relaton-bsi-1.18.0/lib/relaton_bsi/hit_collection.rb:3:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/jerome/.gem/ruby/3.0.0/gems/relaton-bsi-1.18.0/lib/relaton_bsi.rb:11:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/jerome/.gem/ruby/3.0.0/gems/relaton-1.18.1/lib/relaton/registry.rb:29:in `block in register_gems'
	from /home/jerome/.gem/ruby/3.0.0/gems/relaton-1.18.1/lib/relaton/registry.rb:28:in `each'
	from /home/jerome/.gem/ruby/3.0.0/gems/relaton-1.18.1/lib/relaton/registry.rb:28:in `register_gems'
	from /home/jerome/.gem/ruby/3.0.0/gems/relaton-1.18.1/lib/relaton/registry.rb:22:in `initialize'
	from /usr/lib/ruby/3.0.0/singleton.rb:127:in `new'
	from /usr/lib/ruby/3.0.0/singleton.rb:127:in `block in instance'
	from /usr/lib/ruby/3.0.0/singleton.rb:125:in `synchronize'
	from /usr/lib/ruby/3.0.0/singleton.rb:125:in `instance'
	from /home/jerome/.gem/ruby/3.0.0/gems/relaton-1.18.1/lib/relaton/db.rb:6:in `initialize'
	from /home/jerome/.gem/ruby/3.0.0/gems/relaton-1.18.1/lib/relaton/db.rb:552:in `new'
	from /home/jerome/.gem/ruby/3.0.0/gems/relaton-1.18.1/lib/relaton/db.rb:552:in `init_bib_caches'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-standoc-2.8.9/lib/metanorma/standoc/ref_queue.rb:220:in `init_bib_caches'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-standoc-2.8.9/lib/metanorma/standoc/init.rb:103:in `init_biblio'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-standoc-2.8.9/lib/metanorma/standoc/init.rb:12:in `init'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-standoc-2.8.9/lib/metanorma/standoc/base.rb:42:in `document1'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-standoc-2.8.9/lib/metanorma/standoc/base.rb:32:in `document'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-standoc-2.8.9/lib/metanorma/standoc/utils.rb:13:in `convert'
	from /home/jerome/.gem/ruby/3.0.0/gems/asciidoctor-2.0.23/lib/asciidoctor/document.rb:956:in `convert'
	from /home/jerome/.gem/ruby/3.0.0/gems/asciidoctor-2.0.23/lib/asciidoctor/convert.rb:120:in `convert'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-2.0.0/lib/metanorma/input/asciidoc.rb:17:in `process'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-2.0.0/lib/metanorma/processor/processor.rb:21:in `input_to_isodoc'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-2.0.0/lib/metanorma/compile/compile.rb:72:in `process_input_adoc'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-2.0.0/lib/metanorma/compile/compile.rb:54:in `process_input'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-2.0.0/lib/metanorma/compile/compile.rb:32:in `compile'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.10.0/lib/metanorma/cli/compiler.rb:45:in `compile_file'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.10.0/lib/metanorma/cli/compiler.rb:30:in `compile'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.10.0/lib/metanorma/cli/compiler.rb:35:in `compile'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.10.0/lib/metanorma/cli/command.rb:248:in `compile_document'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.10.0/lib/metanorma/cli/command.rb:48:in `block in compile'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.10.0/lib/metanorma/cli/command.rb:48:in `each'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.10.0/lib/metanorma/cli/command.rb:48:in `compile'
	from /home/jerome/.gem/ruby/3.0.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /home/jerome/.gem/ruby/3.0.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from /home/jerome/.gem/ruby/3.0.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/jerome/.gem/ruby/3.0.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /home/jerome/.gem/ruby/3.0.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.10.0/lib/metanorma/cli.rb:34:in `start'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.10.0/exe/metanorma:25:in `block in <top (required)>'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.10.0/exe/metanorma:43:in `<top (required)>'
	from /home/jerome/.gem/ruby/3.0.0/bin/metanorma:25:in `load'
	from /home/jerome/.gem/ruby/3.0.0/bin/metanorma:25:in `<main>'
```

**Comment by andrew2net** [comment]
@opoudjis could you update the version of Relaton in the Metanorma's  gemspec? If Metanorma uses `relaton` then use `"~> 1.18.2"`, if `relaton-cli` then `"~> 1.18.1"`. This will force to install `relaton-bsi:v1.18.1` and `faraday-net_http_persistent:2.1.0`.

**Comment by opoudjis** [comment]
Ok, next release is in a week.

**Comment by opoudjis** [comment]
Please check now?

**Comment by opoudjis** [comment]
Closing
