### ISSUE TITLE
SVG maps not working over absolute path images

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma#394]
Currently, this works:

```
.EXPRESS-G diagram of geometry_schema (1 of 16)

[[geometry_schemaexpg1]]
[.svgmap]
=====
image::geometry_schemaexpg1.svg[]

* <<express:topology_schema>>; 1
* <<express:representation_schema>>; 2
* <<express:measure_schema>>; 3
* <<express:geometry_schema>>; 4
* <<express:geometric_model_schema>>; 5
* <<express:scan_data_3d_shape_model_schema>>; 6
=====
```

But this does not work:
```
.EXPRESS-G diagram of geometry_schema (1 of 16)

[[geometry_schemaexpg1]]
[.svgmap]
======
image::C:/Users/Manuel/Documents/Metanorma/iso-10303-srl/schemas/resources/geometry_schema/geometry_schemaexpg1.svg[]

* <<express:topology_schema>>; 1
* <<express:representation_schema>>; 2
* <<express:measure_schema>>; 3
* <<express:geometry_schema>>; 4
* <<express:geometric_model_schema>>; 5
* <<express:scan_data_3d_shape_model_schema>>; 6
======
```

**Comment by manuelfuenmayor** [comment]
To replicate, use the templates of this PR: https://github.com/metanorma/iso-10303-templates/pull/32, in part 42.

**Comment by opoudjis** [comment]
iiiiinteresting. The relative locations of files has been an acute concern for the Metanorma refactor, as YAMLs are ending up in different places. I am meant to have things that recognise absolute file locations, but I may have forgotten to include one here, or else I may not have used one that understands Windows. I likely won't be able to replicate this on OSX, but I'll test it anyway. (Absolute file locations on OSX and Linux look different to Windows.)

**Comment by opoudjis** [comment]
As asked in Skype, I need your error trace before I can action this, @manuelfuenmayor

**Comment by manuelfuenmayor** [comment]
To be clear, the SVGs are rendered correctly but the links are still numbers.

**Comment by opoudjis** [comment]
Replicated on OSX. If the SVG has an absolute path, its svgmap is not processed. Bizarre behaviour, investigating.

**Comment by opoudjis** [comment]
Absolute path was being left in `<img src="..."><svg>...` even after the svg had already been read in, and the presence of `img/@src` to be re-read in from disk (with its hyperlinks no longer resolved). Declining to re-read in svg from file if img already has an svg child.

**Comment by opoudjis** [comment]
presentation_passthrough_xml is copying the original Semantic XML across, not the Semantic XML recompiled after update_xrefs into a temp directory. This should never have worked, but I'm passing to it now the new file....

**Comment by opoudjis** [comment]
touch wood, seems to be done, although the last fix worries me...

**Comment by opoudjis** [comment]
````
Render Init: 14:45:06
C:/Ruby27-x64/lib/ruby/gems/2.7.0/ruby/2.7.0/bundler/gems/metanorma-95cd35b71f97/lib/metanorma/collection/sectionsplit/sectionsplit.rb:103:in `read': No such file or directory @ rb_sysopen - C:/Users/Manuel/AppData/Local/Temp/document.xml20240606-16308-1l5cxvz.presentation.xml (Errno::ENOENT)
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/ruby/2.7.0/bundler/gems/metanorma-95cd35b71f97/lib/metanorma/collection/sectionsplit/sectionsplit.rb:103:in `sectionsplit_prep'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/ruby/2.7.0/bundler/gems/metanorma-95cd35b71f97/lib/metanorma/collection/sectionsplit/sectionsplit.rb:71:in `sectionsplit'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/ruby/2.7.0/bundler/gems/metanorma-95cd35b71f97/lib/metanorma/collection/filelookup/filelookup_sectionsplit.rb:79:in `sectionsplit'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/ruby/2.7.0/bundler/gems/metanorma-95cd35b71f97/lib/metanorma/collection/filelookup/filelookup_sectionsplit.rb:18:in `process_section_split_instance'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/ruby/2.7.0/bundler/gems/metanorma-95cd35b71f97/lib/metanorma/collection/filelookup/filelookup_sectionsplit.rb:9:in `block in add_section_split'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/ruby/2.7.0/bundler/gems/metanorma-95cd35b71f97/lib/metanorma/collection/filelookup/filelookup_sectionsplit.rb:7:in `each'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/ruby/2.7.0/bundler/gems/metanorma-95cd35b71f97/lib/metanorma/collection/filelookup/filelookup_sectionsplit.rb:7:in `each_with_object'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/ruby/2.7.0/bundler/gems/metanorma-95cd35b71f97/lib/metanorma/collection/filelookup/filelookup_sectionsplit.rb:7:in `add_section_split'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/ruby/2.7.0/bundler/gems/metanorma-95cd35b71f97/lib/metanorma/collection/renderer/renderer.rb:67:in `initialize'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/ruby/2.7.0/bundler/gems/metanorma-95cd35b71f97/lib/metanorma/collection/renderer/renderer.rb:86:in `new'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/ruby/2.7.0/bundler/gems/metanorma-95cd35b71f97/lib/metanorma/collection/renderer/renderer.rb:86:in `render'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/ruby/2.7.0/bundler/gems/metanorma-95cd35b71f97/lib/metanorma/collection/collection.rb:86:in `render'
        from collection.rb:239:in `main'
        from collection.rb:291:in `<main>'
````

**Comment by opoudjis** [comment]
I'm abandoning Tempfile, too risky. I will instead write these second compilations to `tmp_` + filename in the working directory.

**Comment by opoudjis** [comment]
The latest crash on this appears to be a structural issue with 41, which results in the Presentation XML never being compiled; will need to see if this is triggered by the new template.

````
/Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/isodoc-2.10.3/lib/isodoc/class_utils.rb:72:in `nearest_block_parent'
/Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/isodoc-2.10.3/lib/isodoc/class_utils.rb:80:in `start_of_sentence'
/Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/isodoc-2.10.3/lib/isodoc/function/utils.rb:22:in `start_of_sentence'
/Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/isodoc-2.10.3/lib/isodoc/presentation_function/xrefs.rb:168:in `capitalise_xref1'
/Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/isodoc-2.10.3/lib/isodoc/presentation_function/xrefs.rb:164:in `capitalise_xref'
/Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/isodoc-2.10.3/lib/isodoc/presentation_function/xrefs.rb:41:in `anchor_linkend1'
/Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/metanorma-iso-2.7.9/lib/isodoc/iso/presentation_xref.rb:141:in `anchor_linkend1'
/Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/isodoc-2.10.3/lib/isodoc/presentation_function/xrefs.rb:29:in `anchor_linkend'
/Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/isodoc-2.10.3/lib/isodoc/presentation_function/inline.rb:17:in `get_linkend'
/Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/isodoc-2.10.3/lib/isodoc/presentation_function/inline.rb:64:in `xref1'
/Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/isodoc-2.10.3/lib/isodoc/presentation_function/inline.rb:42:in `block in xref'
/Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/nokogiri-1.15.6-arm64-darwin/lib/nokogiri/xml/node_set.rb:235:in `block in each'
/Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/nokogiri-1.15.6-arm64-darwin/lib/nokogiri/xml/node_set.rb:234:in `upto'
/Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/nokogiri-1.15.6-arm64-darwin/lib/nokogiri/xml/node_set.rb:234:in `each'
/Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/isodoc-2.10.3/lib/isodoc/presentation_function/inline.rb:42:in `xref'
/Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/isodoc-2.10.3/lib/isodoc/presentation_xml_convert.rb:90:in `inline'
/Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/isodoc-2.10.3/lib/isodoc/presentation_xml_convert.rb:48:in `conversions'
/Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/isodoc-2.10.3/lib/isodoc/presentation_xml_convert.rb:28:in `convert1'
/Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/metanorma-iso-2.7.9/lib/isodoc/iso/presentation_xml_convert.rb:23:in `convert1'
/Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/isodoc-2.10.3/lib/isodoc/convert.rb:168:in `convert'
/Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/metanorma-iso-2.7.9/lib/metanorma/iso/processor.rb:69:in `output'

````

**Comment by opoudjis** [comment]
svgmap is breaking it, because svgmap does not need to be a block of text. I'll stop looking for the start of a sentence when we hit /target (within svgmap), and I'll also include clauses as a backstop.

**Comment by opoudjis** [comment]
@manuelfuenmayor If you get this compiling, please close this issue

**Comment by opoudjis** [comment]
@manuelfuenmayor If this compiles successfully your side, as it just as on mine, please close this issue. The empty index page is an issue for https://github.com/metanorma/iso-10303/issues/259

**Comment by opoudjis** [comment]
It is compiling successfully with @manuelfuenmayor, but waiting for him to finalise checks.

**Comment by opoudjis** [comment]
Manuel has done the checks, this is now resolved.
