### ISSUE TITLE
Support parallel execution of Metanorma

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#49]
```sh
git clone https://github.com/calconnect/standards.calconnect.org
make distclean
make -j 3 # run 3 jobs at once
```

Output:

* Since all of these input files are in the same directory, the way Metanorma uses the local directory for temporary files (e.g. `htmlstyle.css`) causes race conditions.
* Solution: DO NOT use the local directory as a temporary directory. The document should be should be generated in a new+separate temp directory.

```
cp _input/csd/cc-51005.xml csd && \
	cd csd && \
	bundle exec metanorma -t csd -R cc-51005.rxl -x html,pdf,doc,xml cc-51005.xml
cp _input/csd/cc-51006.xml csd && \
	cd csd && \
	bundle exec metanorma -t csd -R cc-51006.rxl -x html,pdf,doc,xml cc-51006.xml
cp _input/csd/csd-report-conference-36.xml csd && \
	cd csd && \
	bundle exec metanorma -t csd -R csd-report-conference-36.rxl -x html,pdf,doc,xml csd-report-conference-36.xml
[metanorma] processor "standoc" registered
[metanorma] processor "standoc" registered
[metanorma] processor "standoc" registered
[metanorma] processor "iso" registered
[metanorma] processor "iso" registered
[metanorma] processor "iso" registered
[metanorma] processor "ietf" registered
[metanorma] processor "ietf" registered
[metanorma] processor "ietf" registered
[relaton] processor "gbbib" registered
[relaton] processor "gbbib" registered
[relaton] processor "gbbib" registered
[metanorma] processor "gb" registered
[metanorma] processor "gb" registered
[metanorma] processor "gb" registered
[metanorma] processor "csd" registered
[metanorma] processor "csd" registered
[metanorma] processor "csd" registered
[metanorma] processor "csand" registered
[metanorma] processor "csand" registered
[metanorma] processor "csand" registered
[metanorma] processor "m3d" registered
[metanorma] processor "m3d" registered
[metanorma] processor "m3d" registered
[metanorma] processor "rsd" registered
[metanorma] processor "rsd" registered
[metanorma] processor "rsd" registered
[metanorma] processor "acme" registered
[metanorma] processor "acme" registered
[metanorma] processor "acme" registered
[metanorma] processor "unece" registered
[metanorma] processor "unece" registered
[metanorma] processor "unece" registered
[metanorma] processor "mpfd" registered
[metanorma] processor "mpfd" registered
[metanorma] processor "mpfd" registered
[metanorma] processor "nist" registered
[metanorma] processor "nist" registered
[metanorma] processor "nist" registered
[metanorma] processor "ogc" registered
[metanorma] processor "ogc" registered
[metanorma] processor "ogc" registered
[metanorma] Info: gem `metanorma-csd` loaded.
[metanorma] Processing: Metanorma XML input.
[metanorma] Info: gem `metanorma-csd` loaded.
[metanorma] Processing: Metanorma XML input.
[metanorma] Info: gem `metanorma-csd` loaded.
[metanorma] Processing: Metanorma XML input.
bundler: failed to load command: metanorma (/Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bin/metanorma)
Errno::ENOENT: No such file or directory @ rb_sysopen - htmlstyle.css
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/isodoc-0.9.20/lib/isodoc/html_function/html.rb:195:in `read'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/isodoc-0.9.20/lib/isodoc/html_function/html.rb:195:in `htmlstylesheet'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/isodoc-0.9.20/lib/isodoc/html_function/html.rb:205:in `htmlstyle'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/isodoc-0.9.20/lib/isodoc/html_function/html.rb:55:in `html_cleanup'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/isodoc-0.9.20/lib/isodoc/html_function/html.rb:45:in `toHTML'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/isodoc-0.9.20/lib/isodoc/html_function/html.rb:33:in `postprocess'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/isodoc-0.9.20/lib/isodoc/convert.rb:168:in `convert'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/isodoc-0.9.20/lib/isodoc/html_convert.rb:17:in `convert'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-csd-1.1.4/lib/metanorma/csd/processor.rb:32:in `output'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-0.3.11/lib/metanorma/compile.rb:193:in `block in process_extensions'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-0.3.11/lib/metanorma/compile.rb:184:in `each'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-0.3.11/lib/metanorma/compile.rb:184:in `process_extensions'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-0.3.11/lib/metanorma/compile.rb:20:in `compile'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-cli-1.1.6/exe/metanorma:137:in `<top (required)>'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bin/metanorma:23:in `load'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bin/metanorma:23:in `<top (required)>'
make: *** [csd/csd-report-conference-36.rxl] Error 1
make: *** Waiting for unfinished jobs....
bundler: failed to load command: metanorma (/Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bin/metanorma)
Errno::ENOENT: No such file or directory @ rb_sysopen - htmlstyle.css
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/isodoc-0.9.20/lib/isodoc/html_function/html.rb:195:in `read'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/isodoc-0.9.20/lib/isodoc/html_function/html.rb:195:in `htmlstylesheet'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/isodoc-0.9.20/lib/isodoc/html_function/html.rb:205:in `htmlstyle'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/isodoc-0.9.20/lib/isodoc/html_function/html.rb:55:in `html_cleanup'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/isodoc-0.9.20/lib/isodoc/html_function/html.rb:45:in `toHTML'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/isodoc-0.9.20/lib/isodoc/html_function/html.rb:33:in `postprocess'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/isodoc-0.9.20/lib/isodoc/convert.rb:168:in `convert'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/isodoc-0.9.20/lib/isodoc/html_convert.rb:17:in `convert'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-csd-1.1.4/lib/metanorma/csd/processor.rb:32:in `output'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-0.3.11/lib/metanorma/compile.rb:193:in `block in process_extensions'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-0.3.11/lib/metanorma/compile.rb:184:in `each'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-0.3.11/lib/metanorma/compile.rb:184:in `process_extensions'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-0.3.11/lib/metanorma/compile.rb:20:in `compile'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-cli-1.1.6/exe/metanorma:137:in `<top (required)>'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bin/metanorma:23:in `load'
  /Users/myself/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bin/metanorma:23:in `<top (required)>'
make: *** [csd/cc-51006.rxl] Error 1
```

**Comment by ronaldtse** [comment]
This is related to https://github.com/metanorma/metanorma-standoc/issues/53 . 

@abunashir do you have time for this? Thanks!

**Comment by opoudjis** [comment]
Assigned this to @abunashir and @CAMOBAP795. There is no way I am going to get to this in a hurry.

**Comment by CAMOBAP795** [comment]
@opoudjis @ronaldtse I will have a look after https://github.com/metanorma/metanorma/issues/48

**Comment by opoudjis** [comment]
Unassigning myself and @abunashir. @CAMOBAP795 if after a month you haven't gotten to this, assign it back to me.

**Comment by CAMOBAP795** [comment]
Blocked by https://github.com/metanorma/metanorma-standoc/issues/53

**Comment by ronaldtse** [comment]
@CAMOBAP is this possible now?

**Comment by CAMOBAP** [comment]
@opoudjis correct me if I'm wrong, but looks like you recently implemented something in this direction, right?

**Comment by ronaldtse** [comment]
@CAMOBAP have you tried this? Is it now possible? Running two metanorma instances at once?

**Comment by CAMOBAP** [comment]
> @CAMOBAP have you tried this? Is it now possible? Running two metanorma instances at once?

As far as i understood the idea was to compile several documents in parallel, and this functionality was implemented, correct me if I am wrong
