### ISSUE TITLE
Puppeteer/PDF time-out after 30s in metanorma-docker container

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#99]
This can be seen here: https://gitlab.com/metanorma/mn-samples-nist/-/jobs/487780486

This is the huge document with over 1500 formulas, clearly Puppeteer has issues with rendering all of them within 30s, and that's why they fail. This is when PDF output is invoked.

That said, since we're going to abandon Puppeteer, this may be a thing of the past. But for historic reasons, posting here with log:

```
echo "Running locally..."; bundle exec metanorma documents/NIST.SP.800-90B.xml
Running locally...
nil versions are discouraged and will be deprecated in Rubygems 4
Math OOXML 100 of 1536
Math OOXML 200 of 1536
Math OOXML 300 of 1536
Math OOXML 400 of 1536
Math OOXML 500 of 1536
Math OOXML 600 of 1536
Math OOXML 700 of 1536
Math OOXML 800 of 1536
Math OOXML 900 of 1536
Math OOXML 1000 of 1536
Math OOXML 1100 of 1536
Math OOXML 1200 of 1536
Math OOXML 1300 of 1536
Math OOXML 1400 of 1536
Math OOXML 1500 of 1536
bundler: failed to load command: metanorma (/usr/local/bundle/bin/metanorma)
RuntimeError: Navigation timeout of 30000 ms exceeded
TimeoutError: Navigation timeout of 30000 ms exceeded
    at /root/.nvm/versions/node/v12.4.0/lib/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21
  -- ASYNC --
    at Frame.<anonymous> (/root/.nvm/versions/node/v12.4.0/lib/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/root/.nvm/versions/node/v12.4.0/lib/node_modules/puppeteer/lib/Page.js:672:49)
    at Page.<anonymous> (/root/.nvm/versions/node/v12.4.0/lib/node_modules/puppeteer/lib/helper.js:112:23)
    at createPdf (/usr/local/bundle/gems/metanorma-1.0.0/bin/metanorma-pdf.js:16:16)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)

  /usr/local/bundle/gems/metanorma-1.0.0/lib/metanorma/output/pdf.rb:18:in `convert'
  /usr/local/bundle/gems/isodoc-1.0.22/lib/isodoc/pdf_convert.rb:33:in `convert'
  /usr/local/bundle/gems/metanorma-nist-1.0.3/lib/metanorma/nist/processor.rb:36:in `output'
  /usr/local/bundle/gems/metanorma-1.0.0/lib/metanorma/compile.rb:203:in `block in process_extensions'
  /usr/local/bundle/gems/metanorma-1.0.0/lib/metanorma/compile.rb:194:in `each'
  /usr/local/bundle/gems/metanorma-1.0.0/lib/metanorma/compile.rb:194:in `process_extensions'
  /usr/local/bundle/gems/metanorma-1.0.0/lib/metanorma/compile.rb:20:in `compile'
  /usr/local/bundle/gems/metanorma-cli-1.2.10.2/lib/metanorma/cli/compiler.rb:41:in `compile_file'
  /usr/local/bundle/gems/metanorma-cli-1.2.10.2/lib/metanorma/cli/compiler.rb:29:in `compile'
  /usr/local/bundle/gems/metanorma-cli-1.2.10.2/lib/metanorma/cli/compiler.rb:33:in `compile'
  /usr/local/bundle/gems/metanorma-cli-1.2.10.2/lib/metanorma/cli/command.rb:35:in `compile'
  /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /usr/local/bundle/gems/metanorma-cli-1.2.10.2/lib/metanorma/cli.rb:60:in `start'
  /usr/local/bundle/gems/metanorma-cli-1.2.10.2/exe/metanorma:20:in `<top (required)>'
  /usr/local/bundle/bin/metanorma:23:in `load'
  /usr/local/bundle/bin/metanorma:23:in `<top (required)>'
make: *** [Makefile:37: documents/NIST.SP.800-90B.html] Error 1
```

**Comment by opoudjis** [comment]
Well, we had to pick a time to give up on Puppeteer; in fact, that can apply to any external process Metanorma invokes. If we were to retain Puppeteer, we could have set a metanorma option to ignore timeouts.

**Comment by ronaldtse** [comment]
@CAMOBAP795 while you're working with metanorma-pdf.js, could you also help fix this one to extend the Puppeteer time out to 2 minutes (right now it is 30s)? Thanks!

**Comment by CAMOBAP795** [comment]
Done

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP795 ! is the commit pushed? If so can you tag that commit in this issue?

**Comment by CAMOBAP795** [comment]
@ronaldtse sure PR: https://github.com/metanorma/metanorma/pull/101 Commit: https://github.com/metanorma/metanorma/pull/101/commits/a2218be62abb40ed08693a495ce203fc6baf970f
